### ISSUE TITLE
DNAC Command Runner Issue

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#176]
### Execute Commands Across the Network with Cisco DNA Center Platform and Command Runner
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-cmd-run/step/1

>Step 1: Understand Command Runner
>The command runner is a standalone application in DNAC. It also is used as a part of assurance to run commands on devices as a part of a troubleshooting workflow.
>
>Below is an example of an assurance use case. In this case the "show memory platform"  command is used to troubleshoot a memory issue on a device.

How do we run Command Runner?

I found this page in the DNA Center Userguide on page 57.
<img width="468" alt="029" src="https://user-images.githubusercontent.com/50714/66159017-bb5d3080-e5ec-11e9-9116-6ec2fef5c7d4.PNG">

In the UI I do not see the other option.
<img width="358" alt="030" src="https://user-images.githubusercontent.com/50714/66159135-fd867200-e5ec-11e9-9101-13ee8a3edee4.PNG">

**Comment by JoelRiglerIG** [comment]
Seems what is left out - is that the Code Running module has not been added to the Sandboxes.  This is a Sandbox issue as well as a doc omission.

**Comment by annegentle** [comment]
I think having that "assurance use case" screenshot is confusing, since the Learning Lab never goes through the UI for the use case. However if the rest of the Learning Lab works with the Always-on Sandbox, then removing the screenshot might be a good fix? What do you think @Reth11?

**Comment by Reth11** [comment]
@annegentle, Yes, I agree we should remove it as it does not add anything to the lab.

**Comment by JoelRiglerIG** [comment]
@Reth11, @annegentle : 

1) I agree the Assurance screenshot seems to be irrelevant and should be removed. The GUI interface is still of value, as it gives the user a comparison to using the API.   See "User Guide References", below,  for more information on that.  The User Guide confusion is because it changed between 1.2.6 (which is the version of the SandBox) and 1.3.1.0 which is the version of the User Guide referenced in the original issue description. 

2) The instructions make use of assumed Python scripts but do not show them or the request or response structures for the API methods.  This should also be corrected. 


User Guide References

The User Guide reference copied in the original issue description looks like it was extracted from the 1.3.1.0 User Guide (https://www.cisco.com/c/en/us/td/docs/cloud-systems-management/network-automation-and-management/dna-center/1-3-1-0/user_guide/b_cisco_dna_center_ug_1_3_1_0/b_cisco_dna_center_ug_1_3_1_0_chapter_011.html?bookSearch=true#id_68538) and it appears to be correct for that Release. 

The correct User Guide to use is for the release matching that Sandbox - which is Release 1.2.6. 

I did find instructions in the Cisco Digital Network Architecture Center User Guide, Release 1.2.6 (https://www.cisco.com/c/en/us/td/docs/cloud-systems-management/network-automation-and-management/dna-center/1-2-6/user_guide/b_dnac_ug_1_2_6/manage_your_inventory.html?bookSearch=true#id_68538) that matches the DNA Center version at the referenced Sandbox. 

**Step 1 | From the Cisco DNA Center home page, click Inventory.
Step 2 | Select the devices that you want to run commands on.
Step 3 | From the Actions drop-down list, choose Launch Command Runner.**

Alternatively, a user can look under Tools and see Command Runner and execute it that way.  That is documented in another section of the User Guide:
https://www.cisco.com/c/en/us/td/docs/cloud-systems-management/network-automation-and-management/dna-center/1-2-6/user_guide/b_dnac_ug_1_2_6/about_command_runner.html.

**Step 1 | From the Cisco DNA Center home page, click Command Runner in Tools.The Command Runner window appears.
Step 2 | From the Select one or more device(s) drop-down list, choose a device or devices on which to run diagnostic CLI commands.A Device List with your selection appears.
Step 3 | Either select another device to add to the list or click your selected device or devices to close them.
Step 4 | In the Add a Command field, enter a CLI command and click Add.
Step 5 | Click Run Command(s).If successful, a Command(s) executed successfully message appears.
Step 6 | Click the command displayed underneath the device to view the command output.The complete command output is then displayed in the Command Runner window.
Step 7 | Click Copy CLI to copy the command output to your clipboard so that you can paste it to a text file, if necessary.
Step 8 | Click Previous Page to return to the previous window.Note If necessary, click the x symbol next to a device name to remove the device from the device list. Similarly, click the x symbol next to a command to remove the command from the command list.**


---
Other notes with regard to the DNA Center GUI: 

1)   "Inventory" is grouped with the critical 'Tools' which for some reason are in smaller fonts and icons, and can only be found by scrolling to the bottom of the Home page. 

2) Navigation to the 'home' page itself is not obvious - there are no visual clues that tell the user that the 'Cisco' icon and the 'DNA Center' icon are clickable and reset the user view.

3) The 'Actions' dropdown is only displayed after 'selection'. The 'select' referenced above, is to click on the selection box on the left.,  That activates and displays the Action menu (previously hidden). If you click on the device itself, you get more details about the device in a popup but it doesn't select the device.

**Comment by JoelRiglerIG** [comment]
@Reth11 Let me know if the comment/entry above sufficiently answers your question - so that we can remove the "Help Wanted" Label.  We'll convert this issue into one that address the incorrect screenshot for Assurance and uses correct ones for 1.2.6+ and 1.3.x;  and expands the API explanations,  and provide more Python script support.

**Comment by Reth11** [comment]
@JoelRiglerIG, 
Yes, that addresses the issue and works great. I removed the tag for help wanted. Thanks.

**Comment by JoelRiglerIG** [comment]
Substantial rewrite completed in branch ll-issue-176-jrigler (https://github.com/CiscoDevNet/DNAC-101-LL).
However, remaining problem is that provided user (devnetuser) does not have sufficient role to either view Command Runner in GUI, or execute remote commands. The associated python example code fails with a Traceback and when executed in POSTMAN, its clear that the user does not have sufficient role rights.  Response in Postman is:  HTTP 403 (Forbidden), with message: 
{
    "message": "Role does not have valid permissions to access the API"
}

**Comment by annegentle** [comment]
@JoelRiglerIG I'd like to get @kiskander to comment on the intent. Perhaps on a reservation-based Sandbox, the user would have sufficient permissions, so you could revise the LL to use a reservation-based Sandbox. Check with Kareem and see what he thinks.

**Comment by JoelRiglerIG** [comment]
Rewrite of this LL is complete along with an update / correction to referenced PostMan collection.  I rewrote to instruct user to NOT attempt 2nd step on Always On Release 1.2.6 (Read only user) Sandbox.
