### ISSUE TITLE
DNAC Script Missing and Lab Feels as Though It Is Missing Exercises

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#198]
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-template-prg/step/2

I am following along with the lab, except there doesn't seem much to do. The script is not accessible and at the top of the page it says, "It is also possible to create/update templates via API, but that is outside the scope of this learning lab". The lab is turning more into a stand-alone document without any exercises. 

<img width="929" alt="040" src="https://user-images.githubusercontent.com/50714/66437477-6f94f780-e9ef-11e9-8756-572fb4f520f6.PNG">

**Comment by JoelRiglerIG** [comment]
Agreement with issue point.  The key Python script or even portions of the script which presumably contain the key API calls is missing from the doc -  - so this 'step/2' set of instructions has very little value. I'm classifying as a bug - since this omission makes this step in the lab of very little value.

**Comment by vvaliapa** [comment]
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-101-template-prg/cisco-dna-center-and-template-programmer/, this lab is interactive now and exercise is present. Therefore, closing this issue.
