### ISSUE TITLE
Creating Webex Team Bot - Learning Lab Issues

### ISSUE THREAD

**Issue by TomDaviesUK** [CiscoDevNet/learning-labs-issues#63]
Reported by community user:

* Lab: Experiment With Cisco Spark Webhooks: 
     *  Requestb.in service has been discontinued so the lab doesn’t work anymore.
* Lab: Run a Cisco Spark Bot from a Web IDE: 
     * c9.io has been fully migrated to AWS so the free user account no longer exists.  I tried doing the lab using AWS Cloud9 however the UI is quite different so impossible to follow the steps in the lab.
* Lab: Create conversational Chat Bots with Botkit: 
     * Variable SPARK_TOKEN has been modified to ACCESS_TOKEN for Webex Teams, so the steps in the lab won’t work with Botkit.

**Comment by ObjectIsAdvantag** [comment]
Here's a check as of April 4th 2019:

**Lab: Experiment With Cisco Spark Webhooks**
> Requestb.in service has been discontinued so the lab doesn’t work anymore.

GOOD: ngrok is currently used instead of requestb.in, see https://developer.cisco.com/learning/lab/collab-sparkwebhook/step/1

**Lab: Run a Cisco Spark Bot from a Web IDE:**
> c9.io has been fully migrated to AWS so the free user account no longer exists. I tried doing the lab 
using AWS Cloud9 however the UI is quite different so impossible to follow the steps in the lab.

GOOD: this lab has been retired

**Lab: Create conversational Chat Bots with Botkit:**
> Variable SPARK_TOKEN has been modified to ACCESS_TOKEN for Webex Teams, so the steps in the lab won’t work with Botkit.

GOOD: the code supports both variable SPARK_TOKEN and ACCESS_TOKEN, and the instructions use ACCESS_TOKEN only, see https://developer.cisco.com/learning/lab/collab-spark-botkit/step/3

**Comment by ObjectIsAdvantag** [comment]
Thanks @TomDaviesUK for raising these and all actions were taken as you raised these.
Assigning to @klevenstein to close the issue.

**Comment by klevenstein** [comment]
Closing; thanks Stève!
